name: torch17
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.2.89
  - ffmpeg=4.0
  - hdf5=1.10.2
  - imageio=2.6.1
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - opencv=3.4.2
  - pillow=8.3.1
  - pip=21.1.3
  - py-opencv=3.4.2
  - python=3.7.10
  - python-dateutil=2.8.2
  - pytorch=1.7.1
  - scikit-image=0.18.1
  - torchaudio=0.7.2
  - torchvision=0.8.2
  - pip:
    - absl-py==0.15.0
    - accelerate==0.3.0
    - astunparse==1.6.3
    - cachetools==4.2.4
    - charset-normalizer==2.0.3
    - cloudpickle==2.0.0
    - dm-tree==0.1.6
    - flatbuffers==1.12
    - gast==0.3.3
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - googledrivedownloader==0.4
    - grpcio==1.32.0
    - h5py==2.10.0
    - idna==3.2
    - importlib-metadata==4.10.0
    - isodate==0.6.0
    - jinja2==3.0.1
    - joblib==1.0.1
    - markdown==3.3.6
    - markupsafe==2.0.1
    - networkx==2.6.2
    - numpy==1.19.5
    - oauthlib==3.1.1
    - opt-einsum==3.3.0
    - packaging==21.0
    - pandas==1.3.1
    - protobuf==3.19.3
    - pyaml==20.4.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - python-louvain==0.15
    - pytz==2021.1
    - pyyaml==5.4.1
    - rdflib==6.0.0
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - scikit-learn==0.24.2
    - scipy==1.7.0
    - six==1.15.0
    - termcolor==1.1.0
    - threadpoolctl==2.2.0
    - torch-cluster==1.5.9
    - torch-geometric==1.7.2
    - torch-scatter==2.0.7
    - torch-sparse==0.6.9
    - torch-spline-conv==1.2.1
    - tqdm==4.61.2
    - typing-extensions==3.7.4.3
    - urllib3==1.26.6
    - werkzeug==2.0.2
    - wrapt==1.12.1
    - zipp==3.7.0
