name: torch19
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.1.74
  - ffmpeg=4.3
  - h5py=2.10.0
  - hdf5=1.10.5
  - imageio=2.6.1
  - ipykernel=6.4.1
  - ipython=7.27.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.4
  - jupyter=1.0.0
  - jupyter_client=7.0.2
  - jupyter_console=6.4.0
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.1
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - matplotlib-inline=0.1.3
  - notebook=6.4.3
  - numpy=1.20.3
  - numpy-base=1.20.3
  - pandas=1.3.0
  - pillow=8.3.1
  - pip=21.0.1
  - python=3.7.11
  - pytorch=1.9.0
  - pytorch-cluster=1.5.9
  - pytorch-scatter=2.0.8
  - pytorch-sparse=0.6.12
  - pytorch-spline-conv=1.2.1
  - pyyaml=5.4.1
  - scikit-image=0.18.1
  - scikit-learn=0.24.2
  - scipy=1.6.3
  - torchaudio=0.9.0
  - torchfile=0.1.0
  - torchvision=0.10.0
  - tqdm=4.62.2
  - yacs=0.1.6
  - yaml=0.2.5
  - pip:
    - accelerate==0.5.1
    - opencv-python==3.4.2.17
